"""empty message

Revision ID: 23deeded97ce
Revises: 87fe6ee798f8
Create Date: 2025-05-12 23:47:20.598395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23deeded97ce'
down_revision = '87fe6ee798f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_new_password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('temp_new_password')

    # ### end Alembic commands ###
