"""empty message

Revision ID: 87fe6ee798f8
Revises: 626175e31891
Create Date: 2025-05-12 23:23:10.598251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fe6ee798f8'
down_revision = '626175e31891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('code_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('code_verified')
        batch_op.drop_column('code_sent_at')

    # ### end Alembic commands ###
