"""empty message

Revision ID: aef7889c2d18
Revises: 23deeded97ce
Create Date: 2025-05-13 00:27:13.168577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef7889c2d18'
down_revision = '23deeded97ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_new_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verification_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email_code_sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_code_sent_at')
        batch_op.drop_column('email_verification_code')
        batch_op.drop_column('temp_new_email')

    # ### end Alembic commands ###
